version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: ${PHP_IMAGE_NAME}
        container_name: ${PHP_CONTAINER_NAME}
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            PHP_IDE_CONFIG: "serverName=Docker"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: ${NGINX_IMAGE_NAME}
        container_name: ${NGINX_CONTAINER_NAME}
        restart: unless-stopped
        tty: true
        ports:
            - ${APP_EXTERNAL_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network



#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local

